### ISSUE TITLE
Add support for Auth0 for automatic oauth client creation

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-kubernetes#10]
This step is necessary to automatically provision oauth providers for the QHub service. Auth0 supports  [dynamic client registration](https://auth0.com/docs/api-auth/dynamic-client-registration) which will be usefull.

**Comment by costrouc** [comment]
Looks like a custom authenticator should be used for OAuth.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f046cf2b0166d250def3abfa266d06021c65ce6f/jupyterhub/files/hub/jupyterhub_config.py#L350-L360

**Comment by costrouc** [comment]
Demo script for dynamically generating clients 

```
import os
import pprint

from auth0.v3.management import Auth0
from auth0.v3.authentication import GetToken

# https://github.com/auth0/auth0-python/issues/173
# requires creating application that has required scopes
# and machine-to-machine access

domain = os.environ['AUTH0_DOMAIN']
client_id = os.environ['AUTH0_CLIENT_ID']
client_secret = os.environ['AUTH0_CLIENT_SECRET']

# get 24h token
get_token = GetToken(domain)
token = get_token.client_credentials(
    client_id, client_secret, 'https://{}/api/v2/'.format(domain))
mgmt_api_token = token['access_token']


auth0 = Auth0(domain, mgmt_api_token)

# # list connections
# for connection in auth0.connections.all():
#     pprint.pprint(connection)

# # list applications
# for client in auth0.clients.all():
#     pprint.pprint(client)

auth0.clients.create({
    'name': 'QHub Demo 1',
    'description': 'Autoprovisioned client',
    'callbacks': [
        'https://jupyter.asdf.qhub.dev/auth/callback',
    ],
    'app_type': 'regular_web',
})
```

Now next item is to prove that I can integrate an application with jupyterhub

**Comment by costrouc** [comment]
Working oauth with jupyterhub configuration

```
auth:
  admin:
    access: true
    users:
    - "chris.ostrouchov@gmail.com"
  type: custom
  custom:
    className: "oauthenticator.auth0.Auth0OAuthenticator"
    config:
      oauth_callback_url: https://jupyter.do1.qhub.dev/hub/oauth_callback
      client_id: ...
      client_secret: ...
      scope: ['openid', 'email', 'profile']
  whitelist:
    users:
    - dharhas@quansight.com
```
