### ISSUE TITLE
Decide if we should embed theme in jupyterhub docker image

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-kubernetes#8]
Pros:
1.  simplify jupyterhub helm `values.yaml` and reduce complexity on the users end.

```yaml
hub:
  extraConfig:
    01-jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

    customPodHook: |
      c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
      c.JupyterHub.template_vars = {
          'pangeo_hub_title': 'QHub - ${{ cookiecutter.project_name }}',
          'pangeo_hub_subtitle': 'Autoscaling Compute Environment on Digital Ocean',
          'pangeo_welcome': """Welcome to ${{ cookiecutter.endpoint }}. It is maintained by the <a href="http://quansight.com">Quansight staff</a>. The hub's configuration is stored in the github repository based on <a href="https://github.com/Quansight/qhub-kubernetes/">https://github.com/Quansight/qhub-kubernetes/</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/Quansight/qhub-kubernetes//issues">github issue tracker</a>."""
      }
  extraVolumes:
    - name: custom-templates
      gitRepo:
        repository: "https://github.com/Quansight/qhub-jupyterhub-theme.git"
        revision: "53edc55d0bdd5944fb6dee2d10af90da8faf191d"
  extraVolumeMounts:
    - mountPath: /usr/local/share/jupyterhub/custom_templates
      name: custom-templates
      subPath: "qhub-jupyterhub-theme/templates"
    - mountPath: /usr/local/share/jupyterhub/static/extra-assets
      name: custom-templates
      subPath: "qhub-jupyterhub-theme/extra-assets"
```

This way we would only require `template-vars` thus we could provide an easy baked in template that people could use e.g.

```python
c.JupyterHub.template_vars = {
          'pangeo_hub_title': 'QHub - ${{ cookiecutter.project_name }}',
          'pangeo_hub_subtitle': 'Autoscaling Compute Environment on Digital Ocean',
          'pangeo_welcome': """Welcome to ${{ cookiecutter.endpoint }}. It is maintained by the <a href="http://quansight.com">Quansight staff</a>. The hub's configuration is stored in the github repository based on <a href="https://github.com/Quansight/qhub-kubernetes/">https://github.com/Quansight/qhub-kubernetes/</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/Quansight/qhub-kubernetes//issues">github issue tracker</a>."""
      }
```

2. Easy local testing. Currently we have to deploy an entire jupyterhub cluster to test... this is less than ideal.
3. We are already building docker images there is no cost of building an additional one
4. We already theme jupyterlab via a custom image... it is required since it required jupyterlab extensions to be compiled in

Cons:
1. Main point I can see is this may make QHub appear like it is trying to have lockin forcing people to use these custom images.
2. Having a custom jupyterhub image would increase stability but also encourages not moving at the same pace as jupyterhub with is not ideal... 

@yuvipanda do you have thoughts?
