### ISSUE TITLE
Add support for github oauth provider via configuration

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-kubernetes#9]
Adding configuration section:

```
auth:
  type: github
  github:
    clientId: "<replace-me>"
    clientSecret: "<replace-me>"
    callbackUrl: "https://{{ cookiecutter.endpoint }}/hub/oauth_callback"
  admin:
    access: true
    users:
      - ...
  whitelist:
    users:
      - ....
```

Come up with equivalent configuration and keep in mind this will need to also support auto0 later so that we have flexible OAuth. Github OAuth is only a short term solution since it does not support an api for oauth.
